version: '2'
services:
  db:
    image: postgres:9.4.1
    environment:
      POSTGRES_DB: bookings
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: developer
    ports:
      - "5432:5432"

  web:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - 'Booking:/Booking'
    environment:
      - DATABASE_URL:postgres://dev:developer@db:5432/datex_dev?pool=5&encoding=utf-8
